#!/usr/bin/env python3
# Generate src/lite/web_ui_lite.h from a built web-UI dist tree.
#
# The lite firmware serves the OpenEVSE web UI (gui-nightshift, JuiceBox
# profile) as a static asset tree from its embedded web server: GET /index.html
# plus /assets/*.js|.css and the PWA icons/manifest. This mirrors the standard
# ESP32 firmware's web_server_static_files.h model.
#
# Usage:  python3 scripts/gen_web_ui_lite.py <dist-dir>
#   e.g.  python3 scripts/gen_web_ui_lite.py ~/openevse-gui-nightshift/dist-juicebox
#
# Vite gzips the text assets (vite-plugin-compression2, deleteOriginalAssets),
# so most files arrive as *.gz. The served path drops the .gz suffix and we set
# Content-Encoding: gzip for those entries. Binary assets (png/ico) are stored raw.

import os
import sys

CONTENT_TYPES = {
    ".html": "text/html",
    ".js": "application/javascript",
    ".mjs": "application/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".webmanifest": "application/manifest+json",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".txt": "text/plain",
}


def content_type(served_path):
    _, ext = os.path.splitext(served_path)
    return CONTENT_TYPES.get(ext.lower(), "application/octet-stream")


def emit_array(name, data):
    out = ["static const uint8_t %s[] = {" % name]
    line = "  "
    for i, b in enumerate(data):
        line += "0x%02x, " % b
        if (i + 1) % 12 == 0:
            out.append(line.rstrip())
            line = "  "
    if line.strip():
        out.append(line.rstrip())
    out.append("};")
    out.append("static const unsigned %s_LEN = %d;" % (name, len(data)))
    return "\n".join(out)


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: gen_web_ui_lite.py <dist-dir>\n")
        return 1
    dist = os.path.abspath(sys.argv[1])
    if not os.path.isdir(dist):
        sys.stderr.write("not a directory: %s\n" % dist)
        return 1

    files = []
    for root, _dirs, names in os.walk(dist):
        for n in sorted(names):
            full = os.path.join(root, n)
            rel = os.path.relpath(full, dist).replace(os.sep, "/")
            files.append((rel, full))
    files.sort(key=lambda x: x[0])

    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "..", "src", "lite", "web_ui_lite.h")
    out_path = os.path.abspath(out_path)

    arrays = []
    rows = []
    for idx, (rel, full) in enumerate(files):
        with open(full, "rb") as f:
            data = f.read()
        name = "WUI_%d" % idx
        gzip = rel.endswith(".gz")
        served = "/" + (rel[:-3] if gzip else rel)
        arrays.append(emit_array(name, data))
        rows.append(
            '  { "%s", %s, %s_LEN, "%s", %s },'
            % (served, name, name, content_type(served), "true" if gzip else "false")
        )

    hdr = []
    hdr.append("#pragma once")
    hdr.append("#include <stdint.h>")
    hdr.append("// Generated by scripts/gen_web_ui_lite.py from a web-UI dist tree.")
    hdr.append("// Source: gui-nightshift JuiceBox profile (dist-juicebox). DO NOT EDIT.")
    hdr.append("")
    hdr.append("struct LiteStaticFile {")
    hdr.append("  const char    *path;")
    hdr.append("  const uint8_t *data;")
    hdr.append("  unsigned       len;")
    hdr.append("  const char    *content_type;")
    hdr.append("  bool           gzip;")
    hdr.append("};")
    hdr.append("")
    hdr.extend(arrays)
    hdr.append("")
    hdr.append("static const LiteStaticFile LITE_STATIC_FILES[] = {")
    hdr.extend(rows)
    hdr.append("};")
    hdr.append(
        "static const unsigned LITE_STATIC_FILE_COUNT = "
        "sizeof(LITE_STATIC_FILES) / sizeof(LITE_STATIC_FILES[0]);"
    )
    hdr.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(hdr))

    total = sum(len(open(full, "rb").read()) for _rel, full in files)
    sys.stderr.write(
        "wrote %s: %d files, %d bytes embedded\n" % (out_path, len(files), total)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
